// Generated by CoffeeScript 1.11.1
(function() {
  $(document).ready(function() {
    $('.custom-select-open').click(function(e) {
      e.stopPropagation();
      if ($(this).parent().find('.custom-select-list').hasClass('active')) {
        return $(this).parent().find('.custom-select-list').removeClass('active');
      } else {
        $('.custom-select-list').removeClass('active');
        return $(this).parent().find('.custom-select-list').addClass('active');
      }
    });
    $('.custom-select-option .custom-select-value-choose').click(function() {
      var inputName;
      inputName = $(this).parent().parent().data('name');
      $('input[name=' + inputName + ']').val($(this).data('value'));
      $(this).parent().parent().parent().find('.custom-select-value-selected-value').html($(this).html());
      $(this).parent().parent().find('li a').show();
      return $(this).parent().parent().find('li a[data-value="' + $(this).data('value') + '"]').hide();
    });
    $('.custom-select-list').each(function(key, value) {
      return $(this).find('li a[data-value="' + $(this).data('value') + '"]').hide();
    });
    return $('body').click(function() {
      return $('.custom-select-list').removeClass('active');
    });
  });

}).call(this);
